[tox]
no_package = True
env_list = lint,smoke

[testenv]
allowlist_externals =
    poetry

[testenv:lint]
description = Check code against coding style standards
allowlist_externals =
    {[testenv]allowlist_externals}
commands_pre =
    poetry install --only lint,format --no-root
commands =
    poetry check --lock
    poetry run yamllint --no-warnings rockcraft.yaml

[testenv:smoke]
description = smoke test for snap
allowlist_externals =
    {[testenv]allowlist_externals}
commands_pre =
    poetry install --only unit --no-root
commands =
    poetry run pytest -vv --no-header --tb native --log-cli-level=INFO tests/test_smoke.py -s
