[tox]
no_package = True
env_list = lint,smoke

[vars]
tests_path = "{tox_root}/tests"
scripts_path = "{tox_root}/local/scripts"
all_path = {[vars]tests_path} {[vars]scripts_path}

[testenv]
allowlist_externals =
    poetry

[testenv:format]
description = Apply coding style standards to code
commands_pre =
    poetry install --only format --no-root
commands =
    poetry lock
    poetry run ruff check --fix {[vars]all_path}
    poetry run ruff format {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
allowlist_externals =
    {[testenv]allowlist_externals}
commands_pre =
    poetry install --only lint,format --no-root
commands =
    poetry check --lock
    poetry run yamllint --no-warnings rockcraft.yaml
    poetry run codespell {[vars]all_path}
    poetry run ruff check {[vars]all_path}
    poetry run ruff format --check --diff {[vars]all_path}

[testenv:smoke]
description = smoke test for rock
allowlist_externals =
    {[testenv]allowlist_externals}
commands_pre =
    poetry install --only unit --no-root
commands =
    poetry run pytest -vv --no-header --tb native --log-cli-level=INFO tests/test_smoke.py -s
