name: Build ROCK

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup LXD
        uses: canonical/setup-lxd@main
      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic --edge
      - name: Build ROCK
        run: |
          app_version=$(yq '.version' rockcraft.yaml)
          version=$(yq '(.version|split("-"))[0]' rockcraft.yaml)
          base=$(yq '(.base|split("@"))[1]' rockcraft.yaml)
          tag=${version}-${base}_edge
          sed -i "s/${app_version}/${base}/g" rockcraft.yaml
          rockcraft pack
      - name: Upload locally built ROCK artifact
        uses: actions/upload-artifact@v3
        with:
          name: postgresql-rock
          path: charmed-postgresql_*_amd64.rock
