# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  # Triggered on push by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_rock.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

jobs:
  lint-workflows:
    name: Lint .github/workflows/
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v50
    permissions:
      contents: read

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: tox run -e lint
        run: tox run -e lint
    permissions: {}

  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v50
    permissions:
      contents: read

  smoke:
    name: Smoke test rock
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - lint-workflows
      - lint
      - build
    steps:
      - name: Uninstall Postgresql
        run: |
          sudo apt --purge remove postgresql*
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install rockcraft, tox & poetry
        run: |
          sudo snap install rockcraft --classic
          pipx install tox
          pipx install poetry
      - name: Download rock(s)
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Run tests
        run: tox run -e smoke
    permissions: {}
