name: Publish ROCK
on:
  push:
    branches:
      - '[0-9][0-9]-[0-9][0-9].[0-9][0-9]'
  workflow_dispatch:

jobs:
  sbom:
    uses: ./.github/workflows/sbom.yaml
  publish:
    needs: sbom
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker
      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
      - name: Install yq
        run: |
          sudo snap install yq
      - uses: actions/download-artifact@v3
        with:
          name: postgresql-rock
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Import and push to GHCR
        run: |
          version=$(yq '(.version|split("-"))[0]' rockcraft.yaml)
          base=$(yq '(.base|split("@"))[1]' rockcraft.yaml)
          tag=${version}-${base}_edge
          sudo skopeo --insecure-policy copy \
            oci-archive:charmed-postgresql_${tag}_amd64.rock \
            docker-daemon:ghcr.io/canonical/charmed-postgresql:${tag}
          docker push ghcr.io/canonical/charmed-postgresql:${tag}
