# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to GHCR

on:
  push:
    branches:
      - '*-*.04'
    paths:
      - rockcraft.yaml
  workflow_dispatch:

jobs:
  ci-tests:
    name: Tests
    uses: ./.github/workflows/ci.yaml
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: read

  release:
    name: Release rock
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_rock_edge.yaml@v48.0.4
    with:
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      packages: write  # Needed to publish to GitHub Container Registry
      contents: write  # Needed to create git tags

  sbom:
    name: Generate Software Bill of Materials
    needs:
      - ci-tests
      # Run after release so that rock cannot be (maliciously) modified between build & release
      - release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install Syft
        run: |
          gh release --repo anchore/syft download --pattern '*_linux_amd64.deb' --output syft.deb
          sudo apt-get install -y ./syft.deb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download rock package(s)
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ needs.ci-tests.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Generate SBOM(s)
        shell: python
        run: |
          import pathlib
          import subprocess

          for rock_file in pathlib.Path(".").glob("*.rock"):
              subprocess.run(
                  ["syft", rock_file.name, "--output", f"spdx-json={rock_file.name}.spdx.json"],
                  check=True,
              )
      - name: Upload SBOM(s)
        uses: actions/upload-artifact@v7
        with:
          name: sbom-${{ needs.ci-tests.outputs.artifact-prefix }}
          path: '*.spdx.json'
          if-no-files-found: error
    permissions: {}

  trivy:
    needs:
      # Checks the pushed tag
      - release
    name: Trivy Scan
    uses: ./.github/workflows/trivy.yaml
    permissions:
      security-events: write  # Required for uploading Trivy SARIF results
