name: Generate SBOM
on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  sbom:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/4fc17edd146af34ab06f5b0443ef8ddac3aaf076/install.sh | sh -s -- -b /usr/local/bin
      - name: Set version
        run: |
          version=$(yq '(.version|split("-"))[0]' rockcraft.yaml)
          base=$(yq '(.base|split(":"))[1]' rockcraft.yaml)
          echo "version=${version}" >> "$GITHUB_ENV"
      - uses: actions/download-artifact@v3
        with:
          name: postgresql-rock
      - name: Create SBOM
        run: syft charmed-postgresql_${{env.version}}_amd64.rock -o spdx-json=charmed-postgresql_${{env.version}}_amd64.rock.spdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          path: "charmed-postgresql_${{env.version}}_amd64.rock.spdx.json"
          name: charmed-postgresql_${{env.version}}_amd64.rock.spdx.json
